### PR TITLE
Port to OpenSSL 1.1.0

### PR DESCRIPTION
**Pull request by vcrhonek**

### CODE REVIEW

**Comment by kkaempf** [comment]
Please enclose changes with "#if OPENSSL_VERSION_NUMBER ..." to allow building openwsman on older distributions.

**Comment by ajeetraina** [comment]
Any update on this?

**Comment by jeking3** [comment]
It looks like the requested change was made...

**Comment by jeking3** [comment]
This project is missing CI integration with travis which would allow for two build jobs, one with openssl 1.0.x and one with 1.1.x to be created and prove this works.

**Comment by kkaempf** [comment]
openssl 1.1 is supported. closing.

**Pull request closed without merging**
